version: '2'
services:
  crm_maria-app:
    image: crm_maria
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://crm_maria-mariadb:3306/crm_maria?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  crm_maria-mariadb:
    extends:
      file: mariadb.yml
      service: crm_maria-mariadb
