version: '3.1'

services:
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      TZ: Asia/Seoul